# Clonotype comparsion between two paired samples with immunarch package
# Note: use immunarch v0.6.5 to support paired chains
library(immunarch)

# Load clonotypes of the two samples generated by clonotype_filter.R
immdata<-repLoad("P1")

# Gini coeffecient
repDiversity(immdata$data, "gini")

# Public (merged) clone table   
clone_merge<-as.data.frame(pubRep(immdata$data, .verbose = F))

# Replace NA with 0 in the merged table
clone_merge[[4]][is.na(clone_merge[[4]])]<-0
clone_merge[[5]][is.na(clone_merge[[5]])]<-0

# Total clones
tot1<-sum(clone_merge[[4]])
tot2<-sum(clone_merge[[5]])

# Clone proportion
prop1<-clone_merge[[4]] / tot1
prop2<-clone_merge[[5]] / tot2

# P-value with fisher test
pvalue<-apply(clone_merge[c(4, 5)], 1, FUN = function(x) {
	if (x[1] >= 3 | x[2] >= 3) {
		rst<-fisher.test(matrix(c(x[1], x[2], tot1, tot2), nrow = 2))
		return(rst$p.value)
	} else {
		return(NA)
	}
})

# Sort by pvalue
clone_merge<-cbind(clone_merge, prop1 = prop1, prop2 = prop2, pvalue = pvalue)
clone_merge<-clone_merge[order(pvalue),]

# Calculate FDR
clone_select<-clone_merge[!is.na(clone_merge$pvalue),]
FDR<-clone_select$pvalue * nrow(clone_select) / rank(clone_select$pvalue)
clone_select<-cbind(clone_select, FDR = FDR)

# Sometimes the CDR3 is not unique result from homologous IGHV.
# In this case, only the one with the most significant FDR is preserved.
clone_uniq<-aggregate(FDR ~ CDR3.aa, data = clone_select, FUN = min)
clone_select<-merge(x = clone_select, y = clone_uniq, by = c("CDR3.aa", "FDR"))

# Visualize clontype tracking
vis(trackClonotypes(immdata$data, as.character(clone_select$CDR3.aa)))

# Output
write.table(x = clone_select, file = "clone_select.csv", sep = ",", row.names = F)

